"""Add role to Appearance

Revision ID: 239b8548f551
Revises: c2c2c546c60c
Create Date: 2025-06-23 23:17:34.541774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239b8548f551'
down_revision = 'c2c2c546c60c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appearances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appearances', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
