"""Add date to Episode

Revision ID: c2c2c546c60c
Revises: a4d86b7e74d6
Create Date: 2025-06-23 23:15:48.610202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2c2c546c60c'
down_revision = 'a4d86b7e74d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.drop_column('air_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('air_date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_column('date')

    # ### end Alembic commands ###
